### ISSUE TITLE
[FRONTEND] Migrate to Disqus for Comments

### ISSUE THREAD

**Issue by anonfaded** [fadedhood/fadedhood.github.io#4]
We aim to replace **Utterances** with **Disqus** for comments on our website.
The transition involves enabling Disqus via the Jekyll theme's configuration file. Contributors are invited to participate in this migration.

**Comment by GarvAgarwal26** [comment]
Hey can u please assign this issue to me ?

**Comment by anonfaded** [comment]
> Hey can u please assign this issue to me ?

Assigned, thank you for showing interest!
by the way can you share that how you found this repo? :)

**Comment by GarvAgarwal26** [comment]
Hey, can u please elaborate on your issue more clearly...like it will be a lot of help from your side:)

**Comment by anonfaded** [comment]
Sure,
- First when you  fork and clone the repo to your local machine, open the `_config.yml` file which is the configuration file for the website.
- `ctrl + F` and type `utterances` to find the line which you will edit.
You will find this: 
```Js
comments:
  active: utterances 
  disqus:
    shortname: 
```
- Here you have to change two things, replace the utterances to disqus in active variable which will look like this: `active: disqus`.
- In the shortname variable write fadedhood which will look like this: `shortname: fadedhood`.
And you are done!

**Comment by anonfaded** [comment]
@SharkyBytes Bro if you are interested in issue #7, check that out.
Also now tell how you found this repo :)
